// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.UIManager UIManager;
    
    private Gtk.Action FileAction;
    
    private Gtk.Action OpenLocationAction;
    
    private Gtk.Action HelpAction;
    
    private Gtk.Action AboutAction;
    
    private Gtk.Action FileAction1;
    
    private Gtk.Action HelpAction1;
    
    private Gtk.Action OpenLocationAction1;
    
    private Gtk.Action AboutAction1;
    
    private Gtk.Action Action;
    
    private Gtk.Action FileAction2;
    
    private Gtk.Action OpenLocationAction2;
    
    private Gtk.Action HelpAction2;
    
    private Gtk.Action AboutAction2;
    
    private Gtk.Action ViewAction;
    
    private Gtk.Action SortByAction;
    
    private Gtk.Action NameAction;
    
    private Gtk.Action TypeAction;
    
    private Gtk.Action DateAction;
    
    private Gtk.Action OptionsAction;
    
    private Gtk.ToggleAction VSyncEnabledAction;
    
    private Gtk.ToggleAction VertigoEnabledAction;
    
    private Gtk.ToggleAction ShowDetailsAction;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar4;
    
    private Gtk.Entry entry4;
    
    private Gtk.HBox hbox1;
    
    private Gtk.GLWidget glwidget1;
    
    private Gtk.VBox detailsBox;
    
    private Gtk.Table table1;
    
    private Gtk.Entry detailEntryName;
    
    private Gtk.Label detailLabelAccessed;
    
    private Gtk.Label detailLabelContents;
    
    private Gtk.Label detailLabelGroup;
    
    private Gtk.Label detailLabelModified;
    
    private Gtk.Label detailLabelName;
    
    private Gtk.Label detailLabelOwner;
    
    private Gtk.Label detailLabelSize;
    
    private Gtk.Label detailLabelSpace;
    
    private Gtk.Label detailLabelType;
    
    private Gtk.Label detailValueAccessed;
    
    private Gtk.Label detailValueContents;
    
    private Gtk.Label detailValueGroup;
    
    private Gtk.Label detailValueModified;
    
    private Gtk.Label detailValueOwner;
    
    private Gtk.Label detailValueSize;
    
    private Gtk.Label detailValueSpace;
    
    private Gtk.Label detailValueType;
    
    private Gtk.Fixed fixed2;
    
    private Gtk.Fixed fixed3;
    
    private Gtk.Fixed fixed4;
    
    private Gtk.HSeparator hseparator1;
    
    private Gtk.Fixed fixed1;
    
    private Gtk.Label permissionsLabel;
    
    private Gtk.Alignment alignment2;
    
    private Gtk.Table table4;
    
    private Gtk.CheckButton permissionCheckGR;
    
    private Gtk.CheckButton permissionCheckGW;
    
    private Gtk.CheckButton permissionCheckGX;
    
    private Gtk.CheckButton permissionCheckOR;
    
    private Gtk.CheckButton permissionCheckOW;
    
    private Gtk.CheckButton permissionCheckOX;
    
    private Gtk.CheckButton permissionCheckUR;
    
    private Gtk.CheckButton permissionCheckUW;
    
    private Gtk.CheckButton permissionCheckUX;
    
    private Gtk.Label permissionLabelExecute;
    
    private Gtk.Label permissionLabelGroup;
    
    private Gtk.Label permissionLabelOwner;
    
    private Gtk.Label permissionLabelRead;
    
    private Gtk.Label permissionLabelUser;
    
    private Gtk.Label permissionLabelWrite;
    
    private Gtk.Entry findEntry;
    
    private Gtk.Statusbar statusbar6;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.UIManager = new Gtk.UIManager();
        Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
        this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction, null);
        this.OpenLocationAction = new Gtk.Action("OpenLocationAction", Mono.Unix.Catalog.GetString("Open Location"), null, null);
        this.OpenLocationAction.ShortLabel = Mono.Unix.Catalog.GetString("Open Location");
        w1.Add(this.OpenLocationAction, null);
        this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction, null);
        this.AboutAction = new Gtk.Action("AboutAction", Mono.Unix.Catalog.GetString("About"), null, null);
        this.AboutAction.ShortLabel = Mono.Unix.Catalog.GetString("About");
        w1.Add(this.AboutAction, null);
        this.FileAction1 = new Gtk.Action("FileAction1", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction1.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction1, null);
        this.HelpAction1 = new Gtk.Action("HelpAction1", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.HelpAction1.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction1, null);
        this.OpenLocationAction1 = new Gtk.Action("OpenLocationAction1", Mono.Unix.Catalog.GetString("Open Location"), null, null);
        this.OpenLocationAction1.ShortLabel = Mono.Unix.Catalog.GetString("Open Location");
        w1.Add(this.OpenLocationAction1, null);
        this.AboutAction1 = new Gtk.Action("AboutAction1", Mono.Unix.Catalog.GetString("About"), null, null);
        this.AboutAction1.ShortLabel = Mono.Unix.Catalog.GetString("About");
        w1.Add(this.AboutAction1, null);
        this.Action = new Gtk.Action("Action", null, null, null);
        w1.Add(this.Action, null);
        this.FileAction2 = new Gtk.Action("FileAction2", Mono.Unix.Catalog.GetString("File"), null, null);
        this.FileAction2.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w1.Add(this.FileAction2, null);
        this.OpenLocationAction2 = new Gtk.Action("OpenLocationAction2", Mono.Unix.Catalog.GetString("Open Location"), null, null);
        this.OpenLocationAction2.ShortLabel = Mono.Unix.Catalog.GetString("Open Location");
        w1.Add(this.OpenLocationAction2, null);
        this.HelpAction2 = new Gtk.Action("HelpAction2", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.HelpAction2.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w1.Add(this.HelpAction2, null);
        this.AboutAction2 = new Gtk.Action("AboutAction2", Mono.Unix.Catalog.GetString("About"), null, null);
        this.AboutAction2.ShortLabel = Mono.Unix.Catalog.GetString("About");
        w1.Add(this.AboutAction2, null);
        this.ViewAction = new Gtk.Action("ViewAction", Mono.Unix.Catalog.GetString("View"), null, null);
        this.ViewAction.ShortLabel = Mono.Unix.Catalog.GetString("View");
        w1.Add(this.ViewAction, null);
        this.SortByAction = new Gtk.Action("SortByAction", Mono.Unix.Catalog.GetString("Sort by"), null, null);
        this.SortByAction.ShortLabel = Mono.Unix.Catalog.GetString("Sort by");
        w1.Add(this.SortByAction, null);
        this.NameAction = new Gtk.Action("NameAction", Mono.Unix.Catalog.GetString("Name"), null, null);
        this.NameAction.ShortLabel = Mono.Unix.Catalog.GetString("Name");
        w1.Add(this.NameAction, null);
        this.TypeAction = new Gtk.Action("TypeAction", Mono.Unix.Catalog.GetString("Type"), null, null);
        this.TypeAction.ShortLabel = Mono.Unix.Catalog.GetString("Type");
        w1.Add(this.TypeAction, null);
        this.DateAction = new Gtk.Action("DateAction", Mono.Unix.Catalog.GetString("Date"), null, null);
        this.DateAction.ShortLabel = Mono.Unix.Catalog.GetString("Date");
        w1.Add(this.DateAction, null);
        this.OptionsAction = new Gtk.Action("OptionsAction", Mono.Unix.Catalog.GetString("Options"), null, null);
        this.OptionsAction.ShortLabel = Mono.Unix.Catalog.GetString("Options");
        w1.Add(this.OptionsAction, null);
        this.VSyncEnabledAction = new Gtk.ToggleAction("VSyncEnabledAction", Mono.Unix.Catalog.GetString("VSync Enabled"), null, null);
        this.VSyncEnabledAction.Active = true;
        this.VSyncEnabledAction.ShortLabel = Mono.Unix.Catalog.GetString("VSync Enabled");
        w1.Add(this.VSyncEnabledAction, null);
        this.VertigoEnabledAction = new Gtk.ToggleAction("VertigoEnabledAction", Mono.Unix.Catalog.GetString("Vertigo Enabled"), null, null);
        this.VertigoEnabledAction.Active = true;
        this.VertigoEnabledAction.ShortLabel = Mono.Unix.Catalog.GetString("Vertigo Enabled");
        w1.Add(this.VertigoEnabledAction, null);
        this.ShowDetailsAction = new Gtk.ToggleAction("ShowDetailsAction", Mono.Unix.Catalog.GetString("Show Details"), null, null);
        this.ShowDetailsAction.Active = true;
        this.ShowDetailsAction.ShortLabel = Mono.Unix.Catalog.GetString("Show Details");
        w1.Add(this.ShowDetailsAction, null);
        this.UIManager.InsertActionGroup(w1, 0);
        this.AddAccelGroup(this.UIManager.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Glomp");
        this.Icon = Stetic.IconLoader.LoadIcon(this, "gtk-directory", Gtk.IconSize.Menu, 16);
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        this.DefaultWidth = 1024;
        this.DefaultHeight = 600;
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        // Container child vbox1.Gtk.Box+BoxChild
        this.UIManager.AddUiFromString("<ui><menubar name='menubar4'><menu name='FileAction2' action='FileAction2'><menuitem name='OpenLocationAction2' action='OpenLocationAction2'/></menu><menu name='ViewAction' action='ViewAction'><menu name='SortByAction' action='SortByAction'><menuitem name='NameAction' action='NameAction'/><menuitem name='TypeAction' action='TypeAction'/><menuitem name='DateAction' action='DateAction'/></menu><menu name='OptionsAction' action='OptionsAction'><menuitem name='VSyncEnabledAction' action='VSyncEnabledAction'/><menuitem name='VertigoEnabledAction' action='VertigoEnabledAction'/></menu><menuitem name='ShowDetailsAction' action='ShowDetailsAction'/></menu><menu name='HelpAction2' action='HelpAction2'><menuitem name='AboutAction2' action='AboutAction2'/></menu></menubar></ui>");
        this.menubar4 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar4")));
        this.menubar4.Name = "menubar4";
        this.vbox1.Add(this.menubar4);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar4]));
        w2.Position = 0;
        w2.Expand = false;
        w2.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.entry4 = new Gtk.Entry();
        this.entry4.CanFocus = true;
        this.entry4.Name = "entry4";
        this.entry4.IsEditable = true;
        this.entry4.ActivatesDefault = true;
        this.entry4.InvisibleChar = '•';
        this.vbox1.Add(this.entry4);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.entry4]));
        w3.Position = 1;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.glwidget1 = new Gtk.GLWidget();
        this.glwidget1.CanDefault = true;
        this.glwidget1.CanFocus = true;
        this.glwidget1.Events = ((Gdk.EventMask)(768));
        this.glwidget1.Name = "glwidget1";
        this.glwidget1.SingleBuffer = false;
        this.glwidget1.ColorBPP = 32;
        this.glwidget1.AccumulatorBPP = 0;
        this.glwidget1.DepthBPP = 16;
        this.glwidget1.StencilBPP = 0;
        this.glwidget1.Samples = 0;
        this.glwidget1.Stereo = false;
        this.glwidget1.GlVersionMajor = 3;
        this.glwidget1.GlVersionMinor = 0;
        this.hbox1.Add(this.glwidget1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.glwidget1]));
        w4.Position = 0;
        // Container child hbox1.Gtk.Box+BoxChild
        this.detailsBox = new Gtk.VBox();
        this.detailsBox.Name = "detailsBox";
        this.detailsBox.Spacing = 6;
        this.detailsBox.BorderWidth = ((uint)(10));
        // Container child detailsBox.Gtk.Box+BoxChild
        this.table1 = new Gtk.Table(((uint)(12)), ((uint)(3)), false);
        this.table1.Name = "table1";
        this.table1.RowSpacing = ((uint)(6));
        this.table1.ColumnSpacing = ((uint)(6));
        // Container child table1.Gtk.Table+TableChild
        this.detailEntryName = new Gtk.Entry();
        this.detailEntryName.CanFocus = true;
        this.detailEntryName.Name = "detailEntryName";
        this.detailEntryName.IsEditable = true;
        this.detailEntryName.WidthChars = 30;
        this.detailEntryName.InvisibleChar = '•';
        this.table1.Add(this.detailEntryName);
        Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.detailEntryName]));
        w5.LeftAttach = ((uint)(2));
        w5.RightAttach = ((uint)(3));
        w5.XOptions = ((Gtk.AttachOptions)(4));
        w5.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailLabelAccessed = new Gtk.Label();
        this.detailLabelAccessed.Name = "detailLabelAccessed";
        this.detailLabelAccessed.Xalign = 0F;
        this.detailLabelAccessed.LabelProp = Mono.Unix.Catalog.GetString("Accessed:");
        this.detailLabelAccessed.SingleLineMode = true;
        this.table1.Add(this.detailLabelAccessed);
        Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.detailLabelAccessed]));
        w6.TopAttach = ((uint)(8));
        w6.BottomAttach = ((uint)(9));
        w6.XOptions = ((Gtk.AttachOptions)(4));
        w6.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailLabelContents = new Gtk.Label();
        this.detailLabelContents.Name = "detailLabelContents";
        this.detailLabelContents.Xalign = 0F;
        this.detailLabelContents.LabelProp = Mono.Unix.Catalog.GetString("Contents:");
        this.detailLabelContents.SingleLineMode = true;
        this.table1.Add(this.detailLabelContents);
        Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.detailLabelContents]));
        w7.TopAttach = ((uint)(5));
        w7.BottomAttach = ((uint)(6));
        w7.XOptions = ((Gtk.AttachOptions)(4));
        w7.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailLabelGroup = new Gtk.Label();
        this.detailLabelGroup.Name = "detailLabelGroup";
        this.detailLabelGroup.Xalign = 0F;
        this.detailLabelGroup.LabelProp = Mono.Unix.Catalog.GetString("Group:");
        this.detailLabelGroup.SingleLineMode = true;
        this.table1.Add(this.detailLabelGroup);
        Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.detailLabelGroup]));
        w8.TopAttach = ((uint)(11));
        w8.BottomAttach = ((uint)(12));
        w8.XOptions = ((Gtk.AttachOptions)(4));
        w8.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailLabelModified = new Gtk.Label();
        this.detailLabelModified.Name = "detailLabelModified";
        this.detailLabelModified.Xalign = 0F;
        this.detailLabelModified.LabelProp = Mono.Unix.Catalog.GetString("Modified:");
        this.detailLabelModified.SingleLineMode = true;
        this.table1.Add(this.detailLabelModified);
        Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.detailLabelModified]));
        w9.TopAttach = ((uint)(7));
        w9.BottomAttach = ((uint)(8));
        w9.XOptions = ((Gtk.AttachOptions)(4));
        w9.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailLabelName = new Gtk.Label();
        this.detailLabelName.Name = "detailLabelName";
        this.detailLabelName.Xalign = 0F;
        this.detailLabelName.LabelProp = Mono.Unix.Catalog.GetString("Name:");
        this.detailLabelName.SingleLineMode = true;
        this.table1.Add(this.detailLabelName);
        Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.detailLabelName]));
        w10.XOptions = ((Gtk.AttachOptions)(4));
        w10.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailLabelOwner = new Gtk.Label();
        this.detailLabelOwner.Name = "detailLabelOwner";
        this.detailLabelOwner.Xalign = 0F;
        this.detailLabelOwner.LabelProp = Mono.Unix.Catalog.GetString("Owner:");
        this.detailLabelOwner.SingleLineMode = true;
        this.table1.Add(this.detailLabelOwner);
        Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.detailLabelOwner]));
        w11.TopAttach = ((uint)(10));
        w11.BottomAttach = ((uint)(11));
        w11.XOptions = ((Gtk.AttachOptions)(4));
        w11.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailLabelSize = new Gtk.Label();
        this.detailLabelSize.Name = "detailLabelSize";
        this.detailLabelSize.Xalign = 0F;
        this.detailLabelSize.LabelProp = Mono.Unix.Catalog.GetString("Size:");
        this.detailLabelSize.SingleLineMode = true;
        this.table1.Add(this.detailLabelSize);
        Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.detailLabelSize]));
        w12.TopAttach = ((uint)(3));
        w12.BottomAttach = ((uint)(4));
        w12.XOptions = ((Gtk.AttachOptions)(4));
        w12.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailLabelSpace = new Gtk.Label();
        this.detailLabelSpace.Name = "detailLabelSpace";
        this.detailLabelSpace.Xalign = 0F;
        this.detailLabelSpace.LabelProp = Mono.Unix.Catalog.GetString("Space:");
        this.detailLabelSpace.SingleLineMode = true;
        this.table1.Add(this.detailLabelSpace);
        Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.detailLabelSpace]));
        w13.TopAttach = ((uint)(4));
        w13.BottomAttach = ((uint)(5));
        w13.XOptions = ((Gtk.AttachOptions)(4));
        w13.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailLabelType = new Gtk.Label();
        this.detailLabelType.Name = "detailLabelType";
        this.detailLabelType.Xalign = 0F;
        this.detailLabelType.LabelProp = Mono.Unix.Catalog.GetString("Type:");
        this.detailLabelType.SingleLineMode = true;
        this.table1.Add(this.detailLabelType);
        Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.detailLabelType]));
        w14.TopAttach = ((uint)(1));
        w14.BottomAttach = ((uint)(2));
        w14.XOptions = ((Gtk.AttachOptions)(4));
        w14.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailValueAccessed = new Gtk.Label();
        this.detailValueAccessed.Name = "detailValueAccessed";
        this.detailValueAccessed.Xalign = 0F;
        this.table1.Add(this.detailValueAccessed);
        Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.detailValueAccessed]));
        w15.TopAttach = ((uint)(8));
        w15.BottomAttach = ((uint)(9));
        w15.LeftAttach = ((uint)(2));
        w15.RightAttach = ((uint)(3));
        w15.XOptions = ((Gtk.AttachOptions)(4));
        w15.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailValueContents = new Gtk.Label();
        this.detailValueContents.Name = "detailValueContents";
        this.detailValueContents.Xalign = 0F;
        this.detailValueContents.MaxWidthChars = 30;
        this.table1.Add(this.detailValueContents);
        Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.detailValueContents]));
        w16.TopAttach = ((uint)(5));
        w16.BottomAttach = ((uint)(6));
        w16.LeftAttach = ((uint)(2));
        w16.RightAttach = ((uint)(3));
        w16.XOptions = ((Gtk.AttachOptions)(4));
        w16.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailValueGroup = new Gtk.Label();
        this.detailValueGroup.Name = "detailValueGroup";
        this.detailValueGroup.Xalign = 0F;
        this.table1.Add(this.detailValueGroup);
        Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table1[this.detailValueGroup]));
        w17.TopAttach = ((uint)(11));
        w17.BottomAttach = ((uint)(12));
        w17.LeftAttach = ((uint)(2));
        w17.RightAttach = ((uint)(3));
        w17.XOptions = ((Gtk.AttachOptions)(4));
        w17.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailValueModified = new Gtk.Label();
        this.detailValueModified.Name = "detailValueModified";
        this.detailValueModified.Xalign = 0F;
        this.table1.Add(this.detailValueModified);
        Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table1[this.detailValueModified]));
        w18.TopAttach = ((uint)(7));
        w18.BottomAttach = ((uint)(8));
        w18.LeftAttach = ((uint)(2));
        w18.RightAttach = ((uint)(3));
        w18.XOptions = ((Gtk.AttachOptions)(4));
        w18.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailValueOwner = new Gtk.Label();
        this.detailValueOwner.Name = "detailValueOwner";
        this.detailValueOwner.Xalign = 0F;
        this.table1.Add(this.detailValueOwner);
        Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table1[this.detailValueOwner]));
        w19.TopAttach = ((uint)(10));
        w19.BottomAttach = ((uint)(11));
        w19.LeftAttach = ((uint)(2));
        w19.RightAttach = ((uint)(3));
        w19.XOptions = ((Gtk.AttachOptions)(4));
        w19.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailValueSize = new Gtk.Label();
        this.detailValueSize.Name = "detailValueSize";
        this.detailValueSize.Xalign = 0F;
        this.table1.Add(this.detailValueSize);
        Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table1[this.detailValueSize]));
        w20.TopAttach = ((uint)(3));
        w20.BottomAttach = ((uint)(4));
        w20.LeftAttach = ((uint)(2));
        w20.RightAttach = ((uint)(3));
        w20.XOptions = ((Gtk.AttachOptions)(4));
        w20.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailValueSpace = new Gtk.Label();
        this.detailValueSpace.Name = "detailValueSpace";
        this.detailValueSpace.Xalign = 0F;
        this.detailValueSpace.MaxWidthChars = 30;
        this.table1.Add(this.detailValueSpace);
        Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table1[this.detailValueSpace]));
        w21.TopAttach = ((uint)(4));
        w21.BottomAttach = ((uint)(5));
        w21.LeftAttach = ((uint)(2));
        w21.RightAttach = ((uint)(3));
        w21.XOptions = ((Gtk.AttachOptions)(4));
        w21.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.detailValueType = new Gtk.Label();
        this.detailValueType.Name = "detailValueType";
        this.detailValueType.Xalign = 0F;
        this.detailValueType.MaxWidthChars = 30;
        this.table1.Add(this.detailValueType);
        Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table1[this.detailValueType]));
        w22.TopAttach = ((uint)(1));
        w22.BottomAttach = ((uint)(2));
        w22.LeftAttach = ((uint)(2));
        w22.RightAttach = ((uint)(3));
        w22.XOptions = ((Gtk.AttachOptions)(4));
        w22.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.fixed2 = new Gtk.Fixed();
        this.fixed2.HeightRequest = 10;
        this.fixed2.Name = "fixed2";
        this.fixed2.HasWindow = false;
        this.table1.Add(this.fixed2);
        Gtk.Table.TableChild w23 = ((Gtk.Table.TableChild)(this.table1[this.fixed2]));
        w23.TopAttach = ((uint)(2));
        w23.BottomAttach = ((uint)(3));
        w23.LeftAttach = ((uint)(1));
        w23.RightAttach = ((uint)(2));
        w23.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.fixed3 = new Gtk.Fixed();
        this.fixed3.HeightRequest = 10;
        this.fixed3.Name = "fixed3";
        this.fixed3.HasWindow = false;
        this.table1.Add(this.fixed3);
        Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table1[this.fixed3]));
        w24.TopAttach = ((uint)(6));
        w24.BottomAttach = ((uint)(7));
        w24.LeftAttach = ((uint)(1));
        w24.RightAttach = ((uint)(2));
        w24.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table1.Gtk.Table+TableChild
        this.fixed4 = new Gtk.Fixed();
        this.fixed4.HeightRequest = 10;
        this.fixed4.Name = "fixed4";
        this.fixed4.HasWindow = false;
        this.table1.Add(this.fixed4);
        Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table1[this.fixed4]));
        w25.TopAttach = ((uint)(9));
        w25.BottomAttach = ((uint)(10));
        w25.LeftAttach = ((uint)(1));
        w25.RightAttach = ((uint)(2));
        w25.YOptions = ((Gtk.AttachOptions)(4));
        this.detailsBox.Add(this.table1);
        Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.detailsBox[this.table1]));
        w26.Position = 0;
        w26.Expand = false;
        w26.Fill = false;
        // Container child detailsBox.Gtk.Box+BoxChild
        this.hseparator1 = new Gtk.HSeparator();
        this.hseparator1.Name = "hseparator1";
        this.detailsBox.Add(this.hseparator1);
        Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.detailsBox[this.hseparator1]));
        w27.Position = 1;
        w27.Expand = false;
        w27.Fill = false;
        w27.Padding = ((uint)(10));
        // Container child detailsBox.Gtk.Box+BoxChild
        this.fixed1 = new Gtk.Fixed();
        this.fixed1.Name = "fixed1";
        this.fixed1.HasWindow = false;
        this.detailsBox.Add(this.fixed1);
        Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.detailsBox[this.fixed1]));
        w28.Position = 2;
        // Container child detailsBox.Gtk.Box+BoxChild
        this.permissionsLabel = new Gtk.Label();
        this.permissionsLabel.Name = "permissionsLabel";
        this.permissionsLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>Permissions</b>");
        this.permissionsLabel.UseMarkup = true;
        this.permissionsLabel.UseUnderline = true;
        this.detailsBox.Add(this.permissionsLabel);
        Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.detailsBox[this.permissionsLabel]));
        w29.Position = 3;
        w29.Expand = false;
        w29.Fill = false;
        // Container child detailsBox.Gtk.Box+BoxChild
        this.alignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.alignment2.Name = "alignment2";
        this.alignment2.LeftPadding = ((uint)(40));
        this.alignment2.BottomPadding = ((uint)(1));
        // Container child alignment2.Gtk.Container+ContainerChild
        this.table4 = new Gtk.Table(((uint)(4)), ((uint)(4)), true);
        this.table4.Name = "table4";
        this.table4.RowSpacing = ((uint)(6));
        this.table4.ColumnSpacing = ((uint)(6));
        // Container child table4.Gtk.Table+TableChild
        this.permissionCheckGR = new Gtk.CheckButton();
        this.permissionCheckGR.CanFocus = true;
        this.permissionCheckGR.Name = "permissionCheckGR";
        this.permissionCheckGR.Label = "";
        this.permissionCheckGR.DrawIndicator = true;
        this.permissionCheckGR.UseUnderline = true;
        this.permissionCheckGR.Xalign = 0F;
        this.permissionCheckGR.Yalign = 0F;
        this.table4.Add(this.permissionCheckGR);
        Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table4[this.permissionCheckGR]));
        w30.TopAttach = ((uint)(2));
        w30.BottomAttach = ((uint)(3));
        w30.LeftAttach = ((uint)(1));
        w30.RightAttach = ((uint)(2));
        w30.XOptions = ((Gtk.AttachOptions)(0));
        w30.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionCheckGW = new Gtk.CheckButton();
        this.permissionCheckGW.CanFocus = true;
        this.permissionCheckGW.Name = "permissionCheckGW";
        this.permissionCheckGW.Label = "";
        this.permissionCheckGW.DrawIndicator = true;
        this.permissionCheckGW.UseUnderline = true;
        this.permissionCheckGW.Xalign = 0F;
        this.permissionCheckGW.Yalign = 0F;
        this.table4.Add(this.permissionCheckGW);
        Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table4[this.permissionCheckGW]));
        w31.TopAttach = ((uint)(2));
        w31.BottomAttach = ((uint)(3));
        w31.LeftAttach = ((uint)(2));
        w31.RightAttach = ((uint)(3));
        w31.XOptions = ((Gtk.AttachOptions)(0));
        w31.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionCheckGX = new Gtk.CheckButton();
        this.permissionCheckGX.CanFocus = true;
        this.permissionCheckGX.Name = "permissionCheckGX";
        this.permissionCheckGX.Label = "";
        this.permissionCheckGX.DrawIndicator = true;
        this.permissionCheckGX.UseUnderline = true;
        this.permissionCheckGX.Xalign = 0F;
        this.permissionCheckGX.Yalign = 0F;
        this.table4.Add(this.permissionCheckGX);
        Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table4[this.permissionCheckGX]));
        w32.TopAttach = ((uint)(2));
        w32.BottomAttach = ((uint)(3));
        w32.LeftAttach = ((uint)(3));
        w32.RightAttach = ((uint)(4));
        w32.XOptions = ((Gtk.AttachOptions)(0));
        w32.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionCheckOR = new Gtk.CheckButton();
        this.permissionCheckOR.CanFocus = true;
        this.permissionCheckOR.Name = "permissionCheckOR";
        this.permissionCheckOR.Label = "";
        this.permissionCheckOR.DrawIndicator = true;
        this.permissionCheckOR.UseUnderline = true;
        this.permissionCheckOR.Xalign = 0F;
        this.permissionCheckOR.Yalign = 0F;
        this.table4.Add(this.permissionCheckOR);
        Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table4[this.permissionCheckOR]));
        w33.TopAttach = ((uint)(1));
        w33.BottomAttach = ((uint)(2));
        w33.LeftAttach = ((uint)(1));
        w33.RightAttach = ((uint)(2));
        w33.XOptions = ((Gtk.AttachOptions)(0));
        w33.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionCheckOW = new Gtk.CheckButton();
        this.permissionCheckOW.CanFocus = true;
        this.permissionCheckOW.Name = "permissionCheckOW";
        this.permissionCheckOW.Label = "";
        this.permissionCheckOW.DrawIndicator = true;
        this.permissionCheckOW.UseUnderline = true;
        this.permissionCheckOW.Xalign = 0F;
        this.permissionCheckOW.Yalign = 0F;
        this.table4.Add(this.permissionCheckOW);
        Gtk.Table.TableChild w34 = ((Gtk.Table.TableChild)(this.table4[this.permissionCheckOW]));
        w34.TopAttach = ((uint)(1));
        w34.BottomAttach = ((uint)(2));
        w34.LeftAttach = ((uint)(2));
        w34.RightAttach = ((uint)(3));
        w34.XOptions = ((Gtk.AttachOptions)(0));
        w34.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionCheckOX = new Gtk.CheckButton();
        this.permissionCheckOX.CanFocus = true;
        this.permissionCheckOX.Name = "permissionCheckOX";
        this.permissionCheckOX.Label = "";
        this.permissionCheckOX.DrawIndicator = true;
        this.permissionCheckOX.UseUnderline = true;
        this.permissionCheckOX.Xalign = 0F;
        this.permissionCheckOX.Yalign = 0F;
        this.table4.Add(this.permissionCheckOX);
        Gtk.Table.TableChild w35 = ((Gtk.Table.TableChild)(this.table4[this.permissionCheckOX]));
        w35.TopAttach = ((uint)(1));
        w35.BottomAttach = ((uint)(2));
        w35.LeftAttach = ((uint)(3));
        w35.RightAttach = ((uint)(4));
        w35.XOptions = ((Gtk.AttachOptions)(0));
        w35.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionCheckUR = new Gtk.CheckButton();
        this.permissionCheckUR.CanFocus = true;
        this.permissionCheckUR.Name = "permissionCheckUR";
        this.permissionCheckUR.Label = "";
        this.permissionCheckUR.DrawIndicator = true;
        this.permissionCheckUR.UseUnderline = true;
        this.permissionCheckUR.Xalign = 0F;
        this.permissionCheckUR.Yalign = 0F;
        this.table4.Add(this.permissionCheckUR);
        Gtk.Table.TableChild w36 = ((Gtk.Table.TableChild)(this.table4[this.permissionCheckUR]));
        w36.TopAttach = ((uint)(3));
        w36.BottomAttach = ((uint)(4));
        w36.LeftAttach = ((uint)(1));
        w36.RightAttach = ((uint)(2));
        w36.XOptions = ((Gtk.AttachOptions)(0));
        w36.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionCheckUW = new Gtk.CheckButton();
        this.permissionCheckUW.CanFocus = true;
        this.permissionCheckUW.Name = "permissionCheckUW";
        this.permissionCheckUW.Label = "";
        this.permissionCheckUW.DrawIndicator = true;
        this.permissionCheckUW.UseUnderline = true;
        this.permissionCheckUW.Xalign = 0F;
        this.permissionCheckUW.Yalign = 0F;
        this.table4.Add(this.permissionCheckUW);
        Gtk.Table.TableChild w37 = ((Gtk.Table.TableChild)(this.table4[this.permissionCheckUW]));
        w37.TopAttach = ((uint)(3));
        w37.BottomAttach = ((uint)(4));
        w37.LeftAttach = ((uint)(2));
        w37.RightAttach = ((uint)(3));
        w37.XOptions = ((Gtk.AttachOptions)(0));
        w37.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionCheckUX = new Gtk.CheckButton();
        this.permissionCheckUX.CanFocus = true;
        this.permissionCheckUX.Name = "permissionCheckUX";
        this.permissionCheckUX.Label = "";
        this.permissionCheckUX.DrawIndicator = true;
        this.permissionCheckUX.UseUnderline = true;
        this.permissionCheckUX.Xalign = 0F;
        this.permissionCheckUX.Yalign = 0F;
        this.table4.Add(this.permissionCheckUX);
        Gtk.Table.TableChild w38 = ((Gtk.Table.TableChild)(this.table4[this.permissionCheckUX]));
        w38.TopAttach = ((uint)(3));
        w38.BottomAttach = ((uint)(4));
        w38.LeftAttach = ((uint)(3));
        w38.RightAttach = ((uint)(4));
        w38.XOptions = ((Gtk.AttachOptions)(0));
        w38.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionLabelExecute = new Gtk.Label();
        this.permissionLabelExecute.Name = "permissionLabelExecute";
        this.permissionLabelExecute.LabelProp = Mono.Unix.Catalog.GetString("Users");
        this.table4.Add(this.permissionLabelExecute);
        Gtk.Table.TableChild w39 = ((Gtk.Table.TableChild)(this.table4[this.permissionLabelExecute]));
        w39.TopAttach = ((uint)(3));
        w39.BottomAttach = ((uint)(4));
        w39.XOptions = ((Gtk.AttachOptions)(4));
        w39.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionLabelGroup = new Gtk.Label();
        this.permissionLabelGroup.Name = "permissionLabelGroup";
        this.permissionLabelGroup.LabelProp = Mono.Unix.Catalog.GetString("Write");
        this.table4.Add(this.permissionLabelGroup);
        Gtk.Table.TableChild w40 = ((Gtk.Table.TableChild)(this.table4[this.permissionLabelGroup]));
        w40.LeftAttach = ((uint)(2));
        w40.RightAttach = ((uint)(3));
        w40.XOptions = ((Gtk.AttachOptions)(4));
        w40.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionLabelOwner = new Gtk.Label();
        this.permissionLabelOwner.Name = "permissionLabelOwner";
        this.permissionLabelOwner.LabelProp = Mono.Unix.Catalog.GetString("Read");
        this.table4.Add(this.permissionLabelOwner);
        Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table4[this.permissionLabelOwner]));
        w41.LeftAttach = ((uint)(1));
        w41.RightAttach = ((uint)(2));
        w41.XOptions = ((Gtk.AttachOptions)(4));
        w41.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionLabelRead = new Gtk.Label();
        this.permissionLabelRead.Name = "permissionLabelRead";
        this.permissionLabelRead.LabelProp = Mono.Unix.Catalog.GetString("Owner");
        this.table4.Add(this.permissionLabelRead);
        Gtk.Table.TableChild w42 = ((Gtk.Table.TableChild)(this.table4[this.permissionLabelRead]));
        w42.TopAttach = ((uint)(1));
        w42.BottomAttach = ((uint)(2));
        w42.XOptions = ((Gtk.AttachOptions)(4));
        w42.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionLabelUser = new Gtk.Label();
        this.permissionLabelUser.Name = "permissionLabelUser";
        this.permissionLabelUser.LabelProp = Mono.Unix.Catalog.GetString("Execute");
        this.table4.Add(this.permissionLabelUser);
        Gtk.Table.TableChild w43 = ((Gtk.Table.TableChild)(this.table4[this.permissionLabelUser]));
        w43.LeftAttach = ((uint)(3));
        w43.RightAttach = ((uint)(4));
        w43.XOptions = ((Gtk.AttachOptions)(4));
        w43.YOptions = ((Gtk.AttachOptions)(4));
        // Container child table4.Gtk.Table+TableChild
        this.permissionLabelWrite = new Gtk.Label();
        this.permissionLabelWrite.Name = "permissionLabelWrite";
        this.permissionLabelWrite.LabelProp = Mono.Unix.Catalog.GetString("Group");
        this.table4.Add(this.permissionLabelWrite);
        Gtk.Table.TableChild w44 = ((Gtk.Table.TableChild)(this.table4[this.permissionLabelWrite]));
        w44.TopAttach = ((uint)(2));
        w44.BottomAttach = ((uint)(3));
        w44.XOptions = ((Gtk.AttachOptions)(4));
        w44.YOptions = ((Gtk.AttachOptions)(4));
        this.alignment2.Add(this.table4);
        this.detailsBox.Add(this.alignment2);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.detailsBox[this.alignment2]));
        w46.Position = 4;
        w46.Expand = false;
        this.hbox1.Add(this.detailsBox);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.hbox1[this.detailsBox]));
        w47.Position = 1;
        w47.Expand = false;
        w47.Fill = false;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w48.Position = 2;
        // Container child vbox1.Gtk.Box+BoxChild
        this.findEntry = new Gtk.Entry();
        this.findEntry.CanFocus = true;
        this.findEntry.Name = "findEntry";
        this.findEntry.IsEditable = true;
        this.findEntry.InvisibleChar = '•';
        this.vbox1.Add(this.findEntry);
        Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.vbox1[this.findEntry]));
        w49.Position = 3;
        w49.Expand = false;
        w49.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar6 = new Gtk.Statusbar();
        this.statusbar6.Name = "statusbar6";
        this.statusbar6.Spacing = 6;
        this.vbox1.Add(this.statusbar6);
        Gtk.Box.BoxChild w50 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar6]));
        w50.Position = 4;
        w50.Expand = false;
        w50.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.glwidget1.HasDefault = true;
        this.findEntry.Hide();
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.AboutAction2.Activated += new System.EventHandler(this.OnAboutActivated);
        this.NameAction.Activated += new System.EventHandler(this.OnNameSortActivated);
        this.TypeAction.Activated += new System.EventHandler(this.OnTypeSortActivated);
        this.DateAction.Activated += new System.EventHandler(this.OnDateSortActivated);
        this.VSyncEnabledAction.Toggled += new System.EventHandler(this.OnVsyncToggle);
        this.VertigoEnabledAction.Toggled += new System.EventHandler(this.OnHeightColourToggle);
        this.ShowDetailsAction.Toggled += new System.EventHandler(this.OnDetailsVisibleToggled);
        this.entry4.Changed += new System.EventHandler(this.OnPathChanged);
        this.glwidget1.RenderFrame += new System.EventHandler(this.OnGlwidgetRenderFrame);
        this.glwidget1.SizeAllocated += new Gtk.SizeAllocatedHandler(this.OnWidgetResize);
        this.glwidget1.KeyPressEvent += new Gtk.KeyPressEventHandler(this.OnKeyPress);
        this.glwidget1.ButtonReleaseEvent += new Gtk.ButtonReleaseEventHandler(this.OnWidgetClick);
        this.detailEntryName.Activated += new System.EventHandler(this.OnNewNameEntered);
        this.permissionCheckUX.Toggled += new System.EventHandler(this.OnPermissionsToggle);
        this.permissionCheckUW.Toggled += new System.EventHandler(this.OnPermissionsToggle);
        this.permissionCheckUR.Toggled += new System.EventHandler(this.OnPermissionsToggle);
        this.permissionCheckOX.Toggled += new System.EventHandler(this.OnPermissionsToggle);
        this.permissionCheckOW.Toggled += new System.EventHandler(this.OnPermissionsToggle);
        this.permissionCheckOR.Toggled += new System.EventHandler(this.OnPermissionsToggle);
        this.permissionCheckGX.Toggled += new System.EventHandler(this.OnPermissionsToggle);
        this.permissionCheckGW.Toggled += new System.EventHandler(this.OnPermissionsToggle);
        this.permissionCheckGR.Toggled += new System.EventHandler(this.OnPermissionsToggle);
        this.findEntry.FocusOutEvent += new Gtk.FocusOutEventHandler(this.OnFindLoseFocus);
        this.findEntry.Changed += new System.EventHandler(this.OnSearchTextChanged);
        this.findEntry.KeyPressEvent += new Gtk.KeyPressEventHandler(this.OnFindKeyPress);
    }
}
